export const UserActionTypes = {
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_PENDING: "LOGOUT_PENDING",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  CHECK_LOGIN_STATUS_PENDING: "CHECK_LOGIN_STATUS_PENDING",
  CHECK_LOGIN_STATUS_SUCCESS: "CHECK_LOGIN_STATUS_SUCCESS",
  CHECK_LOGIN_STATUS_FAILURE: "CHECK_LOGIN_STATUS_FAILURE",
  REGISTER_PENDING: "REGISTER_PENDING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};